### ISSUE TITLE
Need pretrained model weights

### ISSUE THREAD

**Issue by raghavzns** [jefffang19/LungCancerServerForDoctor#2]
Hi Yu Wen, Can you please share model files ?

**Comment by jefffang19** [comment]
Hi raghavzns, sorry I could not share the weights with you. The model was trained with data under NDA.

Best regards.

**Comment by raghavzns** [comment]
No worries. Can you share the code to train and test the images

**Comment by jefffang19** [comment]
You can refer to this repo: 
https://github.com/jefffang19/eccv_2022_code
In the repo, an open dataset (https://arxiv.org/abs/1705.02315) was used. Feel free to give it a try : )
